POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "alex",
    "nickname": "alexIlha",
    "email": "alexx@email.com",
    "password": "1122334455"
}

###
POST http://localhost:3003/task/create 
Content-Type: application/json 

{
    "title": "projeto-labook",
    "description": "()",
    "deadline": "25/05/2022",
    "authorId": "1b146f8d-7709-4a84-8c3c-7f980e8d4da3" 
}
